"""Compare YAP vs HebPipe segmentations of the 50-sentence sample.

Usage (after yap_client.py and hebpipe_runner.py have produced their outputs):
    python segmentation/compare_segmenters.py

Outputs:
    segmentation/comparison.md  side-by-side per-token diff table (manual review)
    prints agreement stats + per-phenomenon split counts for README.md
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEG = ROOT / "segmentation"

PREFIXES = ["ו", "ש", "כש", "ה", "ל", "ב", "מ"]


def load(name: str) -> list[dict]:
    with open(SEG / name, encoding="utf-8") as f:
        return [json.loads(l) for l in f]


def split_signature(morphemes: list[str]) -> str:
    return " + ".join(morphemes)


def detached_prefixes(morphemes: list[str]) -> list[str]:
    return [m for m in morphemes[:-1] if m in PREFIXES or m == "כש"]


def main() -> None:
    yap, heb = load("out_yap.jsonl"), load("out_hebpipe.jsonl")
    n = min(len(yap), len(heb))
    agree = disagree = 0
    prefix_counts = {"yap": Counter(), "hebpipe": Counter()}
    lines = [
        "# YAP vs HebPipe — token-level comparison\n",
        "_Auto-generated by `compare_segmenters.py`. Only tokens where the two "
        "tools DISAGREE are listed (agreements are counted in the stats)._\n",
        "| # | token | YAP | HebPipe |",
        "|---|-------|-----|---------|",
    ]
    for i in range(n):
        ytoks = {t["token"]: t["morphemes"] for t in yap[i]["tokens"]}
        htoks = {t["token"]: t["morphemes"] for t in heb[i]["tokens"]}
        for tok in ytoks:
            if tok not in htoks:
                continue
            ysig, hsig = split_signature(ytoks[tok]), split_signature(htoks[tok])
            for p in detached_prefixes(ytoks[tok]):
                prefix_counts["yap"][p] += 1
            for p in detached_prefixes(htoks[tok]):
                prefix_counts["hebpipe"][p] += 1
            if ysig == hsig:
                agree += 1
            else:
                disagree += 1
                lines.append(f"| {i+1} | {tok} | {ysig} | {hsig} |")

    total = agree + disagree
    pct = 100 * agree / total if total else 0
    stats = [
        f"\n## Stats\n",
        f"- Tokens compared: {total}, agreement: {agree} ({pct:.1f}%), disagreements: {disagree}",
        f"- Detached prefixes YAP: {dict(prefix_counts['yap'])}",
        f"- Detached prefixes HebPipe: {dict(prefix_counts['hebpipe'])}",
        "\n_Manual rubric (fill in segmentation/README.md): prefix accuracy, "
        "pronominal suffixes, smichut over-splitting, robustness on social-media "
        "text (sentiment sentences are noisy!), speed, installation pain._",
    ]
    (SEG / "comparison.md").write_text("\n".join(lines + stats), encoding="utf-8")
    print("\n".join(stats))
    print(f"\nwrote {SEG / 'comparison.md'} — review the disagreement table manually")


if __name__ == "__main__":
    main()
